spring:
  application:
    name: test-service

server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: test-service.cfapps.eu20.hana.ondemand.com
    prefer-ip-address: false
    # secure-port-enabled: true
    # secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://${EUREKA_SERVER_NAME:localhost}:${EUREKA_SERVER_PORT:8080}/eureka/
      defaultZone: https://eureka-server.cfapps.eu20.hana.ondemand.com:8080/eureka/
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
