spring:
  application:
    name: test-service

server:
    port: ${PORT:8090}

eureka:
  instance:
    hostname: test-service.cfapps.jp10.hana.ondemand.com
    prefer-ip-address: false
    # secure-port-enabled: true
    # secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            # defaultZone: http://${EUREKA_SERVER_NAME:localhost}:${EUREKA_SERVER_PORT:8081}/eureka/
            # defaultZone: https://zuul-api-gateway.cfapps.jp10.hana.ondemand.com/eureka/
            # defaultZone: http://${EUREKA_SERVER_NAME:eureka-server}:${EUREKA_SERVER_PORT:8081}/eureka/
            defaultZone: https://eureka-server.cfapps.jp10.hana.ondemand.com/eureka/
            enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS